### ISSUE TITLE
Why checking shopping-list-react/build/js/shopping-list.js 

### ISSUE THREAD

**Issue by grimcoder** [fedosejev/shopping-list-react-flux#3]
Hi, this is not really an issue but why did you check in shopping-list-react/build/js/shopping-list.js ? I thought it's generated by npm

**Comment by fedosejev** [comment]
@grimcoder you're correct - it is generated by `npm`. Notice that I deploy the shopping list on GitHub Pages (you can see I have `gh-pages` branch as well) and there I need my `js/shopping-list.js` file.
